# Generated by Django 3.2.12 on 2022-11-08 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20221108_0527'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.CharField(max_length=30, null=True)),
                ('image', models.ImageField(null=True, upload_to='cart_img')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('quantity', models.IntegerField(default=1, null=True)),
                ('order', models.BooleanField(default=False, help_text='0-Add, 1-Remove', null=True)),
                ('name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.prodect')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
