# Generated by Django 3.2.12 on 2022-11-08 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='customer',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='cart',
            name='image',
            field=models.ImageField(upload_to='cart_img'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='order',
            field=models.BooleanField(default=False, help_text='0-Add, 1-Remove'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='order_status',
            field=models.IntegerField(choices=[(1, 'new order'), (2, 'old order'), (0, 'not order'), (3, 'cancel order')], default=0),
        ),
        migrations.AlterField(
            model_name='cart',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='cart',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='orderby',
            name='customer',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='orderby',
            name='order_status',
            field=models.IntegerField(choices=[(1, 'success'), (2, 'pending'), (0, 'cancel')], default=2),
        ),
        migrations.AlterField(
            model_name='orderby',
            name='ordered_things',
            field=models.ManyToManyField(to='shop.Cart'),
        ),
        migrations.AlterField(
            model_name='orderby',
            name='tax',
            field=models.FloatField(default=0.18),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='Pictures'),
        ),
        migrations.AlterField(
            model_name='product',
            name='model',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='customer',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='image',
            field=models.ImageField(upload_to='cart_img'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='order',
            field=models.BooleanField(default=False, help_text='0-Add, 1-Remove'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
